--# Problem-01 :- Basic Customer Order Report
/*Pre-Requisites: Before starting with problem solving, please make sure that you have created a database and store sample data	
Level-1: Problem 1 - Basic Customer Order Report
Scenario:
The store manager wants a simple report showing customer orders along with their order dates and status. This report will help track pending and completed orders.
📌 Requirements
1. Retrieve customer first name, last name, order_id, order_date, and order_status.
2. Display only orders with status Pending (1) or Completed (4).
3. Sort the results by order_date in descending order.

🛠️ Technical Constraints
- Use SELECT statement.
- Use WHERE clause with logical operators (AND/OR).
- Use ORDER BY clause.
- Use INNER JOIN between customers and orders tables.

Expectations:
Students should write a correct query using joins and filters, and properly order the result set.
🎯 Learning Outcome 
Understand basic SELECT queries, filtering using WHERE conditions, logical operators, and sorting using ORDER BY clause with INNER JOIN.*/


-----------------------------------------------------

--Create Database
CREATE DATABASE StoreDB;
GO

USE StoreDB;
GO

--Create Tables

--Customers Table

CREATE TABLE customers
(
    customer_id INT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
);

--Orders Table

CREATE TABLE orders
(
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    order_status INT NOT NULL,

    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

--Insert Sample Data

--Insert Customers

INSERT INTO customers VALUES
(1,'Rahul','Sharma'),
(2,'Priya','Verma'),
(3,'Amit','Singh');

--Insert Orders

INSERT INTO orders VALUES
(101,1,'2025-03-01',1),  -- Pending
(102,2,'2025-03-03',4),  -- Completed
(103,1,'2025-03-04',2),  -- Cancelled
(104,3,'2025-03-05',4);  -- Completed

--Final Query

SELECT 
    c.first_name,
    c.last_name,
    o.order_id,
    o.order_date,
    o.order_status
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.order_status = 1
   OR o.order_status = 4
ORDER BY o.order_date DESC;

----------------------------------------------------------------------

--# Problem-02 :- Product Price Listing by Category

/*Level-1: Problem 2 - Product Price Listing by Category
Scenario:
The sales team wants a product listing categorized by product category along with brand details to understand product distribution.
📌 Requirements
1. Display product_name, brand_name, category_name, model_year, and list_price.
2. Filter products with list_price greater than 500.
3. Sort results by list_price in ascending order.

🛠️ Technical Constraints
- Use SELECT statement.
- Use WHERE clause.
- Use ORDER BY clause.
- Use INNER JOIN between products, brands, and categories tables.

Expectations:
Students should correctly join multiple tables and apply filtering and sorting logic.
🎯 Learning Outcome 
Learn multi-table joins, filtering numeric conditions, and sorting query results.*/

-------------------------------------------------------------------------------------------------------

--Create Tables

--Categories Table

CREATE TABLE categories
(
    category_id INT PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL
);

--Brands Table

CREATE TABLE brands
(
    brand_id INT PRIMARY KEY,
    brand_name VARCHAR(100) NOT NULL
);

--Products Table

CREATE TABLE products
(
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    brand_id INT NOT NULL,
    category_id INT NOT NULL,
    model_year INT NOT NULL,
    list_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (brand_id) REFERENCES brands(brand_id),
    FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

--Insert Sample Data

--Insert Categories

INSERT INTO categories VALUES
(1,'Mountain Bikes'),
(2,'Road Bikes'),
(3,'Accessories');

--Insert Brands

INSERT INTO brands VALUES
(1,'Trek'),
(2,'Giant'),
(3,'Specialized');

--Insert Products

INSERT INTO products VALUES
(101,'Trek Marlin 7',1,1,2023,750),
(102,'Giant Escape 3',2,2,2022,450),
(103,'Specialized Rockhopper',3,1,2023,900),
(104,'Trek Domane AL',1,2,2024,1200),
(105,'Bike Helmet',3,3,2023,120);

--Final Query

SELECT 
    p.product_name,
    b.brand_name,
    c.category_name,
    p.model_year,
    p.list_price
FROM products AS p
INNER JOIN brands AS b 
    ON p.brand_id = b.brand_id
INNER JOIN categories AS c 
    ON p.category_id = c.category_id
WHERE p.list_price > 500
ORDER BY p.list_price ASC;

-------------------------------------------------------------------------------------------

--# Problem-03 :- Store Wise Sales Summary

/*Level-2: Problem 1 - Store Wise Sales Summary
Scenario:
The regional manager wants to analyze total sales generated by each store.
📌 Requirements
1. Display store_name and total sales amount.
2. Calculate total sales using (quantity * list_price * (1 - discount)).
3. Include only completed orders (order_status = 4).
4. Group results by store_name.
5. Sort total sales in descending order.

🛠️ Technical Constraints
- Use INNER JOIN between stores, orders, and order_items tables.
- Use GROUP BY clause.
- Use aggregate functions such as SUM().
- Use WHERE clause for filtering.
- Use ORDER BY clause.

Expectations:
Students must write a grouped query with calculated columns and apply proper filtering.
🎯 Learning Outcome 
Understand GROUP BY, aggregate functions, calculated fields, and filtering grouped data.*/

-----------------------------------------------------------------------------

--Stores Table

CREATE TABLE stores
(
    store_id INT PRIMARY KEY,
    store_name VARCHAR(100) NOT NULL
);

--Orders Table

CREATE TABLE orders
(
    order_id INT PRIMARY KEY,
    store_id INT NOT NULL,
    order_status INT NOT NULL,

    FOREIGN KEY (store_id) REFERENCES stores(store_id)
);

--Order Items

CREATE TABLE order_items
(
    item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    quantity INT NOT NULL,
    list_price DECIMAL(10,2) NOT NULL,
    discount DECIMAL(4,2) NOT NULL,

    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

--Sample Data

INSERT INTO stores VALUES
(1,'Central Store'),
(2,'City Mall Store');

INSERT INTO orders VALUES
(101,1,4),
(102,1,1),
(103,2,4);

INSERT INTO order_items VALUES
(1,101,2,500,0.10),
(2,101,1,800,0.05),
(3,103,3,600,0.00);

--Final Query

SELECT 
    s.store_name,
    SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_sales
FROM stores s
INNER JOIN orders o
    ON s.store_id = o.store_id
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 4
GROUP BY s.store_name
ORDER BY total_sales DESC;

-----------------------------------------------------------------------------------

--# Problem-04 :- Product Stock and Sales Analysis

/*Level-2: Problem 2 - Product Stock and Sales Analysis
Scenario:
The inventory manager wants to compare stock availability and total quantity sold for each product.
📌 Requirements
1. Display product_name, store_name, available stock quantity, and total quantity sold.
2. Include products even if they have not been sold (use appropriate join).
3. Group results by product_name and store_name.
4. Sort results by product_name.
🛠️ Technical Constraints
- Use LEFT JOIN between stocks and order_items.
- Use INNER JOIN with products and stores tables.
- Use GROUP BY clause.
- Use SUM() aggregate function.
- Use ORDER BY clause.
Expectations:
Students should correctly use different join types (INNER and LEFT), grouping, and aggregate functions.
🎯 Learning Outcome 
Develop strong understanding of different JOIN types (INNER, LEFT), aggregation, grouping data, and analyzing relational datasets.*/

----------------------------------------------------------------------

--Create Tables

--Products Table

CREATE TABLE products
(
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL
);

--Stores Table

CREATE TABLE stores
(
    store_id INT PRIMARY KEY,
    store_name VARCHAR(100) NOT NULL
);

--Stocks Table

CREATE TABLE stocks
(
    store_id INT,
    product_id INT,
    quantity INT,

    PRIMARY KEY (store_id, product_id),

    FOREIGN KEY (store_id) REFERENCES stores(store_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

--Order_Items Table

CREATE TABLE order_items
(
    item_id INT PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT
);

--Insert Sample 
--Products

INSERT INTO products VALUES
(1,'Laptop'),
(2,'Smartphone'),
(3,'Headphones');

--Stores

INSERT INTO stores VALUES
(1,'Downtown Store'),
(2,'City Mall Store');

--Stocks

INSERT INTO stocks VALUES
(1,1,50),
(1,2,40),
(2,1,30),
(2,3,20);

--Order Items (Sales)

INSERT INTO order_items VALUES
(1,101,1,5),
(2,101,2,3),
(3,102,1,2);

--Final Query

SELECT 
    p.product_name,
    s.store_name,
    st.quantity AS available_stock,
    COALESCE(SUM(oi.quantity),0) AS total_quantity_sold
FROM stocks st
INNER JOIN products p
    ON st.product_id = p.product_id
INNER JOIN stores s
    ON st.store_id = s.store_id
LEFT JOIN order_items oi
    ON st.product_id = oi.product_id
GROUP BY 
    p.product_name,
    s.store_name,
    st.quantity
ORDER BY 
    p.product_name;





